config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#index"

  get 'about', to: 'static_pages#about', as: 'about'

  devise_for :users
  resources :users, only: [ :index, :show ] do
    resources :articles
  end
  resources :articles, only: [ :index, :show, :new, :create, :destroy ]
  
  get '/users/:id', to: 'users#show', as: :user_root
  
  get 'users_search', to: 'users#users_search'
  get 'articles_search', to: 'articles#articles_search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :content, presence: true
end

app/models/static_pages.rb
class StaticPages < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up)  { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [ :show, :edit, :update, :destroy ] 
  before_action :authenticate_user!, except: [ :index, :show ]

  def index
    @articles = Article.all.order("created_at DESC")
  end

  def articles_search
    @articles = Article.where("title LIKE ? OR content LIKE ?", "%#{params[:query]}%", "%#{params[:query]}%")
  end

  def show
  end

  def new 
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      redirect_to user_path(current_user)
    else
      render 'new'
    end
  end

  def destroy
    @article.destroy
    redirect_to user_path(current_user)
  end  

  private

  def find_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about
    @now = Time.now
    @birthday = Time.new(1988, 3, 3)
    @age = @now.year - @birthday.year - ((@now.month > @birthday.month || (@now.month == @birthday.month && @now.day >= @birthday.day)) ? 0 : 1)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [ :show ]
  before_action :authenticate_user!, except: [ :index, :show ]

  def index
    @users = User.all
  end

  def users_search
    @users = User.where("username LIKE ?", "%#{params[:query]}%")
  end

  def show
    @article = @user.articles.build
    @user_articles = @user.articles.all.order("created_at DESC")
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'CrudApp'
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/articles/articles_search.html.erb
<%= provide(:title, 'Articles Search') %>

<div class="text-center mb-5">
  <h1>CRUD Articles</h1>
</div>

<%= link_to 'Back to Articles', articles_path, class: 'btn btn-secondary mb-3' %>

<% @articles.each do |article| %>
<div class="articles py-3 px-3 mb-3">
  <div class="text-center">
    <%= link_to article.title.truncate(50), article_path(article) %>
  </div>

  <hr>

  <div>
    <%= article.content.truncate(300) %>
  </div>

  <hr>

  <div class="text-center">
    <small><%= link_to article.user.username, user_path(article.user) %> | <%= article.created_at.strftime("%B %e, %Y") %></small>  
  </div>
</div>
<% end %>

app/views/articles/index.html.erb
<% provide(:title, 'Articles') %>

<div class="text-center mb-5">
  <h1>CRUD Articles</h1>
</div>

<div class="mb-5">
<%= form_with url: "/articles_search" , method: :get, local: true do |f| %>
  <div class="d-flex flex-row justify-content-center">
    <div class="w-50 me-1">
      <%= f.text_field :query, class: "form-control", placeholder: "Search..." %>
    </div>
    <%= f.submit "Search", class: "btn btn-primary" %>
  </div>
<% end %>  
</div>

<% @articles.each do |article| %>
<div class="articles py-3 px-3 mb-3">
  <div class="text-center">
    <%= link_to article.title.truncate(50), article_path(article) %>
  </div>

  <hr>

  <div>
    <%= article.content.truncate(300) %>
  </div>

  <hr>

  <div class="text-center">
    <small><%= link_to article.user.username, user_path(article.user) %> | <%= article.created_at.strftime("%B %e, %Y") %></small>  
  </div>
</div>
<% end %>

app/views/articles/new.html.erb
<%= provide(:title, 'New Article') %>

<h1>New Article</h1>

<%= render partial: "/shared/article_form" %>

app/views/articles/show.html.erb
<%= provide(:title, "#{@article.title}") %>


<div class="articles py-5 px-3 mb-3">
  <div class="text-center mb-5">
    <h1><%= @article.title %></h1>
  </div>

  <div>
      <p><%= @article.content %></p>
  </div>

  <div class="text-center pt-3">
    <small><%= link_to @article.user.username, user_path(@article.user) %> | <%= @article.created_at.strftime("%B %e, %Y") %></small>  
  </div>
</div>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">  
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">    
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_pack_tag 'brand_icon.ico' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container mb-5">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_article.html.erb
<%= form_with model: @article local: true do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content, size: "60x10" %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/shared/_article_form.html.erb
<div class="text-center">
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    New Article
  </button>
</div>

<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">New Article</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with model: [@user, @article], local: true, class: "row" do |f| %>
          <p>
            <%= f.label :title, class: "col-10 offset-1 col-md-6 offset-md-3" %><br>
            <%= f.text_field :title, class: "col-10 offset-1 col-md-6 offset-md-3" %>
          </p>
          <p>
            <%= f.label :content, class: "col-10 offset-1 col-md-6 offset-md-3" %><br>
            <%= f.text_area :content, size: "60x10", class: "col-10 offset-1 col-md-6 offset-md-3" %>
          </p>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <%= f.submit "Submit", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="copyright">
    <p>Copyright &copy; 2021 The Crud App</p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light">
  <div class="container-fluid">
    <% if user_signed_in? %>
      <%= link_to user_path(current_user), class: "navbar-brand" do%>
        <%= image_pack_tag "nav-logo.png", class:"ms-3 w-25"%>
      <% end %>
    <% else %>
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_pack_tag "nav-logo.png", class:"ms-3 w-25"%>
      <% end %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>      
        <li class="nav-item">
          <%= link_to "Articles", articles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Users", users_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= current_user.username %>
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
              <li>
                <%= link_to "My Page", user_path(current_user), class: "dropdown-item" %>
              </li>
              <li>
                <%= link_to "My Account", edit_user_registration_path(current_user), class: "dropdown-item" %>
              </li>
              
              <li>
                <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
          </li>        
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_sign_up_form.html.erb
<div class="container pt-3 pb-3">
  <div class="text-center">
    <h2>Sign up</h2>
  </div>

  <%= form_for(resource, as: resource_name, url: registration_path(resource_name), class: "row") do |f| %>
    <%= render "devise/shared/error_messages", resource: resource %>

    <div class="field">
      <%= f.label :username, class: "form-label col-md-10 offset-md-1" %><br />
      <%= f.text_field :username, autofocus: false, autocomplete: 'off', class: "col-12 col-md-10 offset-md-1" %>
    </div>

    <div class="field">
      <%= f.label :email, class: "form-label col-md-10 offset-md-1" %><br />
      <%= f.email_field :email, autofocus: false, autocomplete: 'off', class: "col-12 col-md-10 offset-md-1" %>
    </div>

    <div class="field">
      <%= f.label :password, class: "form-label col-md-10 offset-md-1" %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: 'off', class: "col-12 col-md-10 offset-md-1" %>
    </div>

    <div class="field mb-3">
      <%= f.label :password_confirmation, class: "form-label col-12 col-md-10 offset-md-1" %><br />
      <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "col-12 col-md-10 offset-md-1" %>
    </div>

    <div class="actions">
      <%= f.submit "Sign up", class: "col-12 col-md-10 offset-md-1 btn btn-primary"%>
    </div>

    <div class="col-md-10 offset-md-1 mb-3">
      <%= render "devise/shared/links" %>
    </div>
  <% end %>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>

<section>
  <h3>What is CRUD?</h3>
  <p>Create, Read, Update, Delete.</p>
  <p>A description of CRUD in web development.</p>
</section>

<section>
  <h3>What The CRUD App Does</h3>

  <p>CRUD is an acronym. It stands for Create, Read, Update, and Delete.These are programming operations that most all [web] applications utilize. Holding true to CRUD this application, The CRUD App, makes use of users and articles.</p>

  <h3>CREATE</h3>

  <p>Upon your first visit to The CRUD App you will be prompted to sign up (CREATE). This requires a user to chose a unique username, input their email, and input a password to protect their account.</p>

  <h3>READ</h3>

  <p>The CRUD App users, and even non-account holders can view users and read articles. However, in order to specifically search for a user or a specific article a visitor must sign in or sign up.</p>

  <h3>UPDATE</h3>

  <h3>DELETE</h3>

</section>

<section>
  <h2>Tools</h2>
  <p>These are the tools and gems used to create The CRUD App.</p>

  <ul>
    <li>Ruby Programming Language</li>
    <li>Rails - This is commonly referred to as Ruby on Rails.</li>
    <li>Gems</li>
    <aside>RubyGems are small packages of code to assist with programming. These are used to help speed up the development project and not "re-invent the wheel".</aside>
      <ul>
        <li>Devise</li>
        <aside>This is an authentication gem. It is the engine that runs The CRUD App's signup/login functionality.</aside>
      </ul>
    <li>Bootstrap</li>
    <li>Webpack</li>
    <li>Sqlite3 (development) and PostgreSQL (production)</li>
  </ul>
</section>

<section>
  <h2>Why</h2>
  <p>Here will be a description of why I made this app</p>

  <p>I made this app for two reasons. One and the main reason is to practice and improve my understanding of web development with Ruby on Rails. The second reason is to begin the journey of building projects continuously, little by little, and every day pushing new code online. I want to build a portfolio which will help me learn and grow.</p>
</section>

<section>
  <h2>Who</h2>
  <p>This is a description about me</p>
  <p>My name is Matthew Frazier. I am from Kansas, USA. However I live in Tokyo, Japan. I am <%= @age %> years old and work as an English conversation teacher.</p>

  <p>MAYBE ADD THIS SECTION TO AN ABOUT ME PAGE?</p>
  <p>I will also include contact information for:</p>

  <p>Please check me out online, follow my progress and feel free to contact me.</p>

<div class="social-media">
  <ol>
    <li>
      <a href="https://twitter.com/mattfraz38" target="_blank">
        <%= image_pack_tag "twitter.svg"%>      
      </a>
    </li>
    <li>
      <a href="https://www.linkedin.com/in/matthew-frazier-2879bb142/" target="_blank">
        <%= image_pack_tag "linkedin.svg"%>      
      </a>
    </li>

    <li>
      <a href="https://github.com/mattfraz38" target="_blank">
        <%= image_pack_tag "github.svg"%>      
      </a>
    </li>
  </ol>
</div>
</section>

app/views/static_pages/index.html.erb
<% provide(:title, 'Welcome') %>

<div class="row call-to-action d-flex justify-content-evenly">
  <section class="col-lg-6 col-md-12 col-sm-12">
    <div>
      <%= image_pack_tag "welcome_logo.svg", class: "welcome-logo mb-5" %>
    </div>
  </section>

  <section class="sign-up col-lg-4 col-md-12 col-sm-12 h-75 mb-5">
    <%= render "shared/sign_up_form" %>
  </section>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>

<div class="text-center mb-5">
  <h1>CRUD Users</h1>
</div>

<div class="mb-5">
<%= form_with url: "/users_search" , method: :get, local: true do |f| %>
  <div class="d-flex flex-row justify-content-center">
    <div class="w-50 me-1">
      <%= f.text_field :query, class: "form-control", placeholder: "Search..." %>
    </div>
    <%= f.submit "Search", class: "btn btn-primary" %>
  </div>
<% end %>  
</div>

<table class="table table-striped text-center">
  <thead>
    <tr>
      <th>Username</th>
      <th>Number of Articles</th>
      <th>Joined Date</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.username, user_path(user) %></td>
      <td><%= user.articles.count %></td>
      <td><%= user.created_at.strftime("%B %e, %Y") %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/search.html.erb
<h1>Search Results</h1>
    <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.username, user_path(user) %></td>
      <td><%= user.articles.count %></td>
      <td><%= user.created_at.strftime("%B %e, %Y") %></td>
    </tr>
    <% end %>

app/views/users/show.html.erb
<% provide(:title, "#{@user.username}") %>

<div class="text-center mb-5">
  <% if @user == current_user %>
    <h1>Welcome <%= @user.username %>!</h1>
  <% else %>
    <h1>Welcome to <%= @user.username.pluralize %> Page!</h1>
  <% end %>
  <div class="mt-3">
    <small>Member since: <%= @user.created_at.strftime("%B %e, %Y") %></small>
  </div>
</div>

<% if @user == current_user %>
  <div class="new-article py-5">
    <h2 class="text-center mb-5">What's on your mind?</h2>
    <%= render 'shared/article_form' %>
  </div>
<% end %>

<hr class="my-5">

<div class="text-center mb-5">
  <% if @user == current_user %>
    <% if @user.articles.count > 0 %>
      <h3>My Works</h3>
    <% else %>
      <h3>Add an Article!</h3>
    <% end %>
  <% else %>
    <h3><%= @user.username.pluralize %> Works</h3>
  <% end %>
</div>

<section class="mb-5">
  <% @user_articles.each do |article| %>
    <% if article.title && article.content %>
      <div class="articles py-5 px-4 mb-3">
        <h2 class="text-center"><%= article.title %></h2>
        <hr>
        <p><%= article.content %></p>
        <hr>
        <small><%= article.created_at.strftime("%B %e, %Y") %></small>

        <% if @article.user == current_user %>
          <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger float-end" %>
        <% end %>

      </div>
    <% end %>
  <% end %>
</section>

app/views/users/users_search.html.erb
<%= provide(:title, 'Users Search') %>

<div class="text-center mb-5">
  <h1>CRUD Users</h1>
</div>

<%= link_to 'Back to Users', users_path, class: 'btn btn-secondary mb-3' %>

<table class="table table-striped text-center">
  <thead>
    <tr>
      <th>Username</th>
      <th>Number of Articles</th>
      <th>Joined Date</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.username, user_path(user) %></td>
      <td><%= user.articles.count %></td>
      <td><%= user.created_at.strftime("%B %e, %Y") %></td>
    </tr>
    <% end %>
  </tbody>
</table>